name: frontend-admin-pr

on:
  pull_request:
    branches:
    - "main"
    paths:
    - "frontend/admin/**"

jobs:
  frontend-admin-pr-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./frontend/admin"
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        cache-dependency-path: "./frontend/admin/package-lock.json"
        node-version: ${{ matrix.node-version }}
        cache: "npm"
    - name: Install packages
      run: npm ci
    - name: Build
      run: npm run build
    - name: Lint
      run: npm run lint